server:
  port: 8001 #服务端口
#spring相关配置
spring:
  application:
    name: cloud-provide-payment #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库驱动包
    url: jdbc:mysql://127.0.0.1/mcroservice?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
#mybatis:配置
mybatis:
  mapperLocations: classpath:dao/*.xml
  type-aliases-package: com.buba.springcloud.pojo    # 所有pojo别名类所在包
#eureka配置
eureka:
  client:
    register-with-eureka: true   #表示是否将自己注册进eureka  默认为true
    fetch-registry: true #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    service-url:
      #单机配置
      defaultZone: http://localhost:7001/eureka